languageCode = "de"
languageName = "Deutsch"
weight = 2
title = "Nikita Aull"

[params]
  displayName = "Deutsch"
  isoCode = "de"

[params.author]
  name = "Nikita Aull"
  image = "img/author.jpg"
  headline = "DevSecOps Engineer, Softwareentwickler, IT-Enthusiast"
  bio = "Sichere Infrastruktur aufbauen, Code schreiben, Dinge kaputt machen, um sie staerker zu machen."
  links = [
    { github = "https://github.com/au11n" },
    { telegram = "https://t.me/aullblog" },
  ]
