languageCode = "en"
languageName = "English"
weight = 1
title = "Nikita Aull"

[params]
  displayName = "English"
  isoCode = "en"

[params.author]
  name = "Nikita Aull"
  image = "img/author.jpg"
  headline = "DevSecOps Engineer, Software Developer, IT Enthusiast, Dreamer"
  bio = "Building secure infrastructure, writing code, breaking systems"
  links = [
    { github = "https://github.com/au11n" },
    { telegram = "https://t.me/aullblog" },
  ]
