[[main]]
  name = "Блог"
  pageRef = "posts"
  weight = 10

[[main]]
  name = "Проекты"
  pageRef = "projects"
  weight = 20

[[main]]
  name = "Обо мне"
  pageRef = "about"
  weight = 30

[[main]]
  name = "Инструменты"
  pageRef = "uses"
  weight = 40

[[main]]
  name = "Архив"
  pageRef = "archive"
  weight = 50

[[main]]
  name = "Поиск"
  pageRef = "search"
  weight = 60

[[main]]
  name = "Теги"
  pageRef = "tags"
  weight = 70

