[[main]]
  name = "Blog"
  pageRef = "posts"
  weight = 10

[[main]]
  name = "Projekte"
  pageRef = "projects"
  weight = 20

[[main]]
  name = "Ueber mich"
  pageRef = "about"
  weight = 30

[[main]]
  name = "Tags"
  pageRef = "tags"
  weight = 40
