[[main]]
  name = "Блог"
  pageRef = "posts"
  weight = 10

[[main]]
  name = "Проекты"
  pageRef = "projects"
  weight = 20

[[main]]
  name = "Обо мне"
  pageRef = "about"
  weight = 30

[[main]]
  name = "Теги"
  pageRef = "tags"
  weight = 40

[[main]]
  identifier = "search"
  name = "Поиск"
  weight = 50
  [main.params]
    action = "search"

[[main]]
  identifier = "locale"
  weight = 60
  [main.params]
    action = "locale"

[[main]]
  identifier = "appearance"
  weight = 70
  [main.params]
    action = "appearance"
