description = "Nikita Aull - DevSecOps Engineer, Software Developer"

[author]
  name = "Nikita Aull"
  headline = "DevSecOps Engineer, Software Developer, IT Enthusiast"
  image = "img/author.jpg"
  links = [
    { github = "https://github.com/au11n" },
    { telegram = "https://t.me/aullblog" },
    { linkedin = "https://www.linkedin.com/in/aull-nikita-78973327b" },
  ]
